import { renderHamburger } from "./hamburger.js";
import { renderAccordion } from "./accordion.js";
import { renderCkeditor } from "./ckeditor.js";
import { renderAmount } from "./amount-button.js";
import { renderNotification } from "./notification.js";
import { renderProduct } from "./product.js";
import { renderSelectTabs } from "./select-tabs";
import { renderTabs } from "./tabs.js";
import { renderForm } from "./form.js";
import { renderMenu } from "./menu.js";
import { renderCart } from "./cart.js";

renderAccordion();
renderAmount();
renderCkeditor();
renderHamburger();
renderNotification();
renderProduct();
renderSelectTabs();
renderTabs();
renderForm();
renderMenu();
renderCart();